sudo: required
language: java
jdk:
- openjdk11
before_install:
- openssl aes-256-cbc -K $encrypted_e2cf4b6252f0_key -iv $encrypted_e2cf4b6252f0_iv
  -in travis/codesigning.asc.enc -out travis/codesigning.asc -d
- rm "${JAVA_HOME}/lib/security/cacerts"
- ln -s /etc/ssl/certs/java/cacerts "${JAVA_HOME}/lib/security/cacerts"
script:
- |
  set -e
  if [ "$TRAVIS_BRANCH" = 'master' ] && [ "$TRAVIS_PULL_REQUEST" == 'false' ]; then
     ./mvnw clean package
  fi
notifications:
  slack:
    secure: nwQtLuopCrl8ZJ1W+GD8VxpLbHSY+1xIEwterCMEhG7tHqTMdfGv2CpuhWFrV8oLKnuFozCXJGi2YzUiQk27bFb+zDQCxRQAWqUcynq/zoQV+1UqIGX/aHGb9o9GlyUS+vH0xa0MsgytyGyBJ2cqPVW3bCil/BkaPCu/g16RZf6zV/o20Rxbl3kAjQk0eTjXPqdPKQsV7nMDn8ObKTowiw94M/g0kHsXI9etuwvakQ4Sxmhz9XUKK2abn8RCiPYdhIAkcINa6rSkn/OVqNZQJqgPwy0Ra/9f2rHsiH+YDq48yFmzOROw8rrMy35AKKUPbvTE2Xu6PlnSQVa5R80124i8pf32Pt6yJ2ehDWV8ADWyWoxWruH6E+3UgTBWD/Apx7HzchNyRbnaM75xB8BaNiWecIQdnIpEPHYwd1Of7UrSdCkm8ADEZq5CzogsX0thKOlIgkHxcAJRwzAT+6m6l7qYXHUU/aV0SEU0L7dtkLCfROTU57+vqTjs++hEd+zx+/bZMXyWky1IMl9JL2aaAvgUuube3P6vHRP6dHQip9kRPm+hpkkHvkhNir75y0wfXifiHpfSTp1McjZnP1I+5hMIBALxpEs6abpXbNHvwa16+a5CSlJI0Cj44uz7jD+IJwHiBKGHw2ReYEmyjkWRcXaky0HSqNlJTapmNk3qIr0=
env:
  global:
  - OSSRH_JIRA_USERNAME=navikt
  - secure: N87aRf8iP/OaOakhR8GFZhlTs+v7vlRkOcDEF2XGbR9GFKUmB5dmdbI3VDV6UBVakC9aCXyUvSYll82uTesg1pgo20AMMEbJ46ENUPmxc8zcZuU5KuubBlXsI29xV7/05Q3vH5HHx7JwLcrrkOg6IRGw20pdtaXP71zNXuT5vDWjQgJx/X1l50hBWVm58VeclX184m0Ijp3P5UaREnw2l20nCV69DQLcQGUq6aHIhb/CaWAdRyIve5atuH5QoceNbYy5oUdCX5tCM/BebAObJOMFuRh+j7FDS6mq7+ykYEIHtc6BXFyidXLwMMJGqphbWklN+Lh1rvO7/tVUbyTJ6V4U0fpfpz5e+5kv5WYIuSOIIkVnx+xDZyB5Zf9A8PxQF+JbpVx+qFMYeznIIUYkap23wEq6jXhC3fGGzKNYH/deXbMFBaSTuGxpreE8WC83iRfs+vwTaGYN3ruu/KpnapC6L5mYAIJeg/5zkMeDjICl4B1H1GG2uryWhHVyRoACruz4FIbR0vt4Q9ieqTd4ThRA83AHlc+bQJ+WQkv9U0txnZnt1ca++yhE+CWUgHjMHWW0p8o51DF6yiu9soSiA0GND8eaY2sZmK2J+UG9qgvZjpKZwMSrFdnRJv7dIHOiYWBphsriJgJLeoKSJhNCZY7wCsrtE6W1tagAapYSLcE=
  - GPG_KEY_NAME=navikt
  - secure: o8eLbthWlFUjLJ+xBsoDyKgI4b3EQIP2qal3HqRngwPrzWFjFMt6B3ANldFvVCvtGRT4AcNynZ5C4mtzczYEGf2xGjeOymthBso2BQjiecqjFIe/eI5Uhokq7TlBvQgMi/ppZgd2CBSbp0Rhu+7Lf65mBMOo+mDDuw1j3xKncfjMXv5lec9nPhLJHKgZ3P85UUfmSERxDCon01c1VrrATilxiCfg+txd6hxqojV8fgFPaJKSogCkmZxLa2W3B5dH//AedLtHm/kQEIZFwbSXM+QXD6K25OGNJX2H51A+LVYStNk2f28id1C43a1tsB8aSiu3wXGh4e23P5bpQC33nY5vV6GfhApx9nwJ7Gy4p4fTjqjkoNRSknsthJPhoGXZDyxppf7pyVRidfgV+zefj509bn8epA+qqiltddHYvdjUbS6nq9ZMPrVm7GFJJDTXjqtJNXl134VXa2Q2to26sIaeeJiQn+q9w3+5Umwk/rRyVQn5QU4FNtEZnt2rUDEd7Wd1vUN+cgNO725aGwu7PASN+e2mH7CzfL6zqxKQ6jqJtsl5uzSAm6JUOcwBKhvdmjsvM62JjhV7OXTaWSuzjjoGrDWiZ93f5WLv9s92bGa8TSKVVF/TXNCcPsV5ZUgBBMeg09VMt3hPsz3ufMe66CjQ/3JI5r8OdGsbiQEgN9U=
