sudo: required
language: java
jdk:
- openjdk11
before_install:
- openssl aes-256-cbc -K $encrypted_e2cf4b6252f0_key -iv $encrypted_e2cf4b6252f0_iv
  -in travis/secrets.tar.enc -out travis/secrets.tar -d
- tar xvf travis/secrets.tar -C ./travis
- git clone https://github.com/navikt/github-apps-support.git
- export PATH=`pwd`/github-apps-support/bin:$PATH
- export GH_TOKEN=$(generate-installation-token.sh `generate-jwt.sh ./travis/helseci.key
  $GITHUB_APP_ID`)
- export COMMIT_SHORT=$(git rev-parse --short HEAD)
- export ORIGINAL_COMMITTER=$(git log -1 --pretty=format:'%an <%ae>')
- echo -e "machine github.com\n  login $GH_TOKEN" > ~/.netrc
- rm "${JAVA_HOME}/lib/security/cacerts"
- ln -s /etc/ssl/certs/java/cacerts "${JAVA_HOME}/lib/security/cacerts"
script:
- mvn clean install
- |
  set -e
  if [ "$TRAVIS_BRANCH" = 'master' ] && [ "$TRAVIS_PULL_REQUEST" == 'false' ]; then
     echo "Importing GPG key into keyring"
     gpg --fast-import travis/codesigning.asc
     awk '{$1=$1+1}1' version.prop     
     mv version.prop.nu version.prop
     mvn versions:set -DnewVersion="$(cat lov.prop).$(cat version.prop)" 
     git add version.prop pom.xml
     git commit -m"bumped version automatically"
     git push https://x-access-token:$GH_TOKEN@github.com/navikt/helse-streams.git HEAD:master 

     echo "Running release"
     mvn --settings travis/settings.xml deploy -Prelease -DskipTests=true
  fi
notifications:
  slack:
    secure: nwQtLuopCrl8ZJ1W+GD8VxpLbHSY+1xIEwterCMEhG7tHqTMdfGv2CpuhWFrV8oLKnuFozCXJGi2YzUiQk27bFb+zDQCxRQAWqUcynq/zoQV+1UqIGX/aHGb9o9GlyUS+vH0xa0MsgytyGyBJ2cqPVW3bCil/BkaPCu/g16RZf6zV/o20Rxbl3kAjQk0eTjXPqdPKQsV7nMDn8ObKTowiw94M/g0kHsXI9etuwvakQ4Sxmhz9XUKK2abn8RCiPYdhIAkcINa6rSkn/OVqNZQJqgPwy0Ra/9f2rHsiH+YDq48yFmzOROw8rrMy35AKKUPbvTE2Xu6PlnSQVa5R80124i8pf32Pt6yJ2ehDWV8ADWyWoxWruH6E+3UgTBWD/Apx7HzchNyRbnaM75xB8BaNiWecIQdnIpEPHYwd1Of7UrSdCkm8ADEZq5CzogsX0thKOlIgkHxcAJRwzAT+6m6l7qYXHUU/aV0SEU0L7dtkLCfROTU57+vqTjs++hEd+zx+/bZMXyWky1IMl9JL2aaAvgUuube3P6vHRP6dHQip9kRPm+hpkkHvkhNir75y0wfXifiHpfSTp1McjZnP1I+5hMIBALxpEs6abpXbNHvwa16+a5CSlJI0Cj44uz7jD+IJwHiBKGHw2ReYEmyjkWRcXaky0HSqNlJTapmNk3qIr0=
env:
  global:
  - GITHUB_APP_ID=19726
  - OSSRH_JIRA_USERNAME=navikt
  - secure: f46xV4hq/nZiYU5XNhm1KRDcNDbnd+h/TyaawY7u2p+6rkQwMChOcbYQH5EHCeSOm0C9Pc7E2+w/jbhd2bwy5u4To3VEMhBckzSOp4KyKih39ko+t7E3a4HzeU1Szo1Zx+ovOjeSisiVy/AwIlt8hKqxuk7q5p2q2iTXvt7EdLnhUgGOXYE4uoj/EXliIjCq6CUyh40KKLOunRaAlGILWpG3dPOhOP1WxYTMBeTuEgFtaa2FVMsM9BsGzchbZYyxiudGe0mV7wgTI7gwVye/wZjNRrhrBdVyXdxYHXJHIrn7U6aafoelDI3zPEG/B3HE/DJEpqFxMENB93bD8FpnJmnsXpjDfI3P2HsWdFYBVpeRZp1jGgzGEyRg/0iGFpJdn3RCbijj7oFSsrVsmV0FzWpsCVFPmG0RsoQW/lnyyaA93pXBeb5T2p+jenmENy4t+qqHjLZRPNgpA9B5sP5qKpa4sZmYVXpLEDsVAgJ+cSwkoA9ZrwjTtBdIDgSFo7nk8OsVM0jqoFBP6NHmO8Mh+ocO/HuKWSE1noU1h8WYc9/XBvKgLxzF5xs7s9IFknLx6LFK7qwWweFK0yCqXtv6HYXiUJzVtb9jZhuYV8La25Tm4Dakiu8DuUfX/HPcUn0x4XN1d31vCe5bGOBaIfRqv42gKkSAn+qDaRaTaBRosgI=
  - GPG_KEY_NAME=navikt
  - secure: OzhJ49mcHHGQc29THAD4RcTgUL4SRbj0SUBSJ8P/aHezfEAdRTvKf8Lp1ZX9hdXGxOhjSPy1hOpvB+7czjnPd+n8l9zefI/7VZDnJ15i++Isyan12LdZVArng3YSENUBYxjF67weUUCwQZdNn9OtBJXLhrk3g60gT/c4U27aMyL2RmuJNOreWI6/C9MyQ24gZ/2j1CXKWScfC5nh8BE8tL+A3E+09iNWSyDiHBjVowRzmJIGdQ5+ePHVFDa9zG4DqLp7U/lfDMYB9gCbu77MuWYdk7i0z6LvEMPw0IJnFefMYG+fwXBISjiMn7zRGjD55R/aiKvMe+PEyjFdU+rzDUDQE+gxdGBJS3iTWjKO4J3ZS/nplPgHMnB+SpOLCQG5lKVJBN1oCosvN5RbRWbyZt40q5S6AX184SLo1UN5TylictOiyucg5HjfEzrE70OaLFeNh0vQnw+ir5m4y1wCkXn0X8b+75uCIuhKTDMWyodhi/EPGNABubr720KO0hX+GufTBls5osTlZBDT0GNQlzlEIrj9xnOhzGNr0SdiETo4FLz3AT55bJfxMk8uHPPRWPi4sM3b/bdyffOCZfIASfH+/JnfYigwrZ3r3uZyCKVp7crp8BLWiBG8ncHM9YTyTZqiss9OaXuIQ/Q2PHLPh+dm4R+oADeGYtytu3AmQo0=
