name: release

on:
   push:
      branches:
         - master

jobs:
   "build and release":
      runs-on: ubuntu-latest
      steps:
         - name: Dump GitHub context
           env:
              GITHUB_CONTEXT: ${{ toJson(github) }}
           run: echo "$GITHUB_CONTEXT"
         - name: Dump job context
           env:
              JOB_CONTEXT: ${{ toJson(job) }}
           run: echo "$JOB_CONTEXT"
         - name: Dump runner context
           env:
              RUNNER_CONTEXT: ${{ toJson(runner) }}
           run: echo "$RUNNER_CONTEXT"
         - name: Dump steps context
           env:
              STEPS_CONTEXT: ${{ toJson(steps) }}
           run: echo "$STEPS_CONTEXT"
         - uses: actions/checkout@v1
         - uses: actions/setup-java@v1
           with:
              java-version: '11.x'
         - name: create version number
           run: |
              echo $(echo $GITHUB_SHA | cut -c1-7) > .version
         - name: test and build
           run: ./mvnw clean install
         - name: set version
           run: ./mvnw versions:set -DnewVersion="$(cat .version)"
         - name: upload artifact
           run: ./mvnw --settings settings.xml deploy -X -DskipTests=true
           env:
              GITHUB_USERNAME: x-access-token
              GITHUB_PASSWORD: ${{ secrets.GITHUB_ACCESS_TOKEN }}
